# Generated by Django 4.2 on 2025-09-28 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Guias", "0001_initial"),
        ("Certificacion", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Guia_Certificacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Id_Certificacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Certificacion.certificacion",
                    ),
                ),
                (
                    "Id_Guia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Guias.guia"
                    ),
                ),
            ],
            options={
                "db_table": "Guia_Certificacion",
            },
        ),
    ]
