# Generated by Django 4.2 on 2025-09-24 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Guia', '0001_initial'),
        ('Certificacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guia_Sertificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_Certificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Certificacion.certificacion')),
                ('Id_Guia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guia.guia')),
            ],
            options={
                'db_table': 'Guia_Certificacion',
            },
        ),
    ]
