# Generated by Django 4.2 on 2025-09-28 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Reserva", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Actividad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CodigoActividad", models.CharField(max_length=10)),
                ("NombreActividad", models.CharField(max_length=100)),
                (
                    "IdReserva",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Reserva.reserva",
                    ),
                ),
            ],
            options={
                "db_table": "Actividad",
            },
        ),
    ]
