# Generated by Django 4.2 on 2025-09-24 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Reserva', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resenia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('Calificacion', models.IntegerField()),
                ('fecha_comentario', models.DateField()),
                ('Id_Reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reserva.reserva')),
            ],
            options={
                'db_table': 'Resenia',
            },
        ),
    ]
