# Generated by Django 4.2 on 2025-09-24 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='certificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('institucion', models.CharField(max_length=100)),
                ('fecha_emicion', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('archivo', models.FileField(upload_to='Certificaciones/')),
            ],
            options={
                'db_table': 'certificacion',
            },
        ),
    ]
