# Generated by Django 4.2 on 2025-09-28 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Persona", "0001_initial"),
        ("Reserva", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Codigo_Reserva", models.CharField(max_length=10)),
                ("Fecha_Actual", models.DateField()),
                ("Fecha_Reserva", models.DateField()),
                ("Precio", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "Id_Persona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Persona.persona",
                    ),
                ),
                (
                    "Id_Reserva",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Reserva.reserva",
                    ),
                ),
            ],
            options={
                "db_table": "Reservacion",
            },
        ),
    ]
