# Generated by Django 4.2 on 2025-09-24 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=18)),
                ('Nombre1', models.CharField(max_length=50)),
                ('Nombre2', models.CharField(max_length=50)),
                ('Apellido1', models.CharField(max_length=50)),
                ('Apellido2', models.CharField(max_length=50)),
                ('Edad', models.IntegerField()),
                ('Sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('ND', 'Prefiero no decirlo')], default='Masculino', max_length=20, verbose_name='Sexo')),
                ('Telefono', models.CharField(max_length=20, verbose_name='Telefono')),
                ('Dirrecion', models.CharField(max_length=200, verbose_name='Direccion')),
                ('is_Active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'db_table': 'Guia',
            },
        ),
    ]
