# Generated by Django 4.2 on 2025-09-28 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Persona",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Identificacion",
                    models.CharField(max_length=20, verbose_name="Identificacion"),
                ),
                (
                    "Turista",
                    models.CharField(
                        choices=[("NAC", "Nacional"), ("INT", "Internacional")],
                        default="Nacional",
                        max_length=14,
                        verbose_name="Turista",
                    ),
                ),
                (
                    "Nombre",
                    models.CharField(max_length=50, verbose_name="Primer_Nombre"),
                ),
                (
                    "Nombre2",
                    models.CharField(max_length=50, verbose_name="Segundo_Nombre"),
                ),
                (
                    "Apellido1",
                    models.CharField(max_length=50, verbose_name="Primer_Apellido"),
                ),
                (
                    "Apellido2",
                    models.CharField(max_length=50, verbose_name="Segundo_Apellido"),
                ),
                ("Edad", models.IntegerField(verbose_name="Edad")),
                (
                    "Sexo",
                    models.CharField(
                        choices=[
                            ("M", "Masculino"),
                            ("F", "Femenino"),
                            ("ND", "Prefiero no decirlo"),
                        ],
                        default="Masculino",
                        max_length=20,
                        verbose_name="Sexo",
                    ),
                ),
                ("is_Active", models.BooleanField(default=True, verbose_name="Activo")),
            ],
            options={
                "db_table": "persona",
            },
        ),
    ]
